---
# ── Kafka KRaft — apache/kafka:3.9.0 ─────────────────────────────────────────
# Single combined broker+controller node, no persistence, no auth.
# Replaces bitnami/kafka Helm chart for dev environment.
# Topic provisioning is handled by the kafka-init Job below.
#
# NOTE: apache/kafka does NOT read KAFKA_* environment variables automatically
# (unlike the Bitnami image). Configuration is applied by patching
# server.properties directly in both the init container and the main container.
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.dd-dev.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: kafka-format
          image: apache/kafka:3.9.0
          command:
            - /bin/bash
            - -c
            - |
              # apache/kafka ignores KAFKA_* env vars — patch server.properties directly.
              PROPS=/opt/kafka/config/kraft/server.properties

              sed -i "s|^advertised.listeners=.*|advertised.listeners=PLAINTEXT://kafka.dd-dev.svc.cluster.local:9092|" "$PROPS"
              sed -i "s|^listeners=.*|listeners=PLAINTEXT://:9092,CONTROLLER://:9093|" "$PROPS"
              sed -i "s|^listener.security.protocol.map=.*|listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT|" "$PROPS"
              sed -i "s|^controller.quorum.voters=.*|controller.quorum.voters=1@localhost:9093|" "$PROPS"
              sed -i "s|^log.dirs=.*|log.dirs=/tmp/kraft-combined-logs|" "$PROPS"
              sed -i "s|^node.id=.*|node.id=1|" "$PROPS"

              grep -q "^offsets.topic.replication.factor"           "$PROPS" || echo "offsets.topic.replication.factor=1"           >> "$PROPS"
              grep -q "^transaction.state.log.replication.factor"   "$PROPS" || echo "transaction.state.log.replication.factor=1"   >> "$PROPS"
              grep -q "^transaction.state.log.min.isr"              "$PROPS" || echo "transaction.state.log.min.isr=1"              >> "$PROPS"
              grep -q "^auto.create.topics.enable"                  "$PROPS" || echo "auto.create.topics.enable=true"               >> "$PROPS"

              echo "--- Patched server.properties (relevant lines) ---"
              grep -E "^(advertised\.listeners|listeners|node\.id|log\.dirs|controller\.quorum)" "$PROPS"
              echo "--------------------------------------------------"

              # Format storage (idempotent — safe to re-run)
              CLUSTER_ID=$(/opt/kafka/bin/kafka-storage.sh random-uuid)
              /opt/kafka/bin/kafka-storage.sh format \
                --ignore-formatted \
                -t "$CLUSTER_ID" \
                -c "$PROPS"
          volumeMounts:
            - name: kafka-logs
              mountPath: /tmp/kraft-combined-logs
      containers:
        - name: kafka
          image: apache/kafka:3.9.0
          command:
            - /bin/bash
            - -c
            - |
              # Re-apply patches so the broker starts with the correct listeners.
              # The init container already patched the file, but we re-apply here
              # as a safety measure in case the image is ever updated.
              PROPS=/opt/kafka/config/kraft/server.properties

              sed -i "s|^advertised.listeners=.*|advertised.listeners=PLAINTEXT://kafka.dd-dev.svc.cluster.local:9092|" "$PROPS"
              sed -i "s|^listeners=.*|listeners=PLAINTEXT://:9092,CONTROLLER://:9093|" "$PROPS"
              sed -i "s|^listener.security.protocol.map=.*|listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT|" "$PROPS"
              sed -i "s|^controller.quorum.voters=.*|controller.quorum.voters=1@localhost:9093|" "$PROPS"
              sed -i "s|^log.dirs=.*|log.dirs=/tmp/kraft-combined-logs|" "$PROPS"
              sed -i "s|^node.id=.*|node.id=1|" "$PROPS"

              grep -q "^offsets.topic.replication.factor"           "$PROPS" || echo "offsets.topic.replication.factor=1"           >> "$PROPS"
              grep -q "^transaction.state.log.replication.factor"   "$PROPS" || echo "transaction.state.log.replication.factor=1"   >> "$PROPS"
              grep -q "^transaction.state.log.min.isr"              "$PROPS" || echo "transaction.state.log.min.isr=1"              >> "$PROPS"
              grep -q "^auto.create.topics.enable"                  "$PROPS" || echo "auto.create.topics.enable=true"               >> "$PROPS"

              echo "--- server.properties (relevant lines) ---"
              grep -E "^(advertised\.listeners|listeners|node\.id|log\.dirs)" "$PROPS"
              echo "------------------------------------------"

              exec /opt/kafka/bin/kafka-server-start.sh "$PROPS"
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - name: client
              containerPort: 9092
            - name: controller
              containerPort: 9093
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: kafka-logs
              mountPath: /tmp/kraft-combined-logs
      volumes:
        - name: kafka-logs
          emptyDir: {}
---
# ── Topic provisioning Job ────────────────────────────────────────────────────
# Runs after Kafka is ready and creates the content-events topic.
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  labels:
    app: kafka
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic-init
          image: apache/kafka:3.9.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              until /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --list > /dev/null 2>&1; do
                echo "  Kafka not ready yet, retrying in 5s..."
                sleep 5
              done
              echo "Kafka is ready. Creating topic content-events..."
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --create \
                --if-not-exists \
                --topic content-events \
                --partitions 1 \
                --replication-factor 1 \
                --config retention.ms=86400000 \
                --config cleanup.policy=delete
              echo "Topic created successfully."
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --describe --topic content-events