---
# ── Kafka KRaft — apache/kafka:3.9.0 ─────────────────────────────────────────
# Single combined broker+controller node, no persistence, no auth.
# Replaces bitnami/kafka Helm chart for dev environment.
# Topic provisioning is handled by the kafka-init Job below.
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  # Override key properties; rest use image defaults
  KAFKA_NODE_ID: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.dd-dev.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
      targetPort: 9092
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
        - name: kafka-format
          image: apache/kafka:3.9.0
          command:
            - /bin/bash
            - -c
            - |
              # Generate a cluster ID and format storage (idempotent if already formatted)
              CLUSTER_ID=$(/opt/kafka/bin/kafka-storage.sh random-uuid)
              /opt/kafka/bin/kafka-storage.sh format \
                --ignore-formatted \
                -t "$CLUSTER_ID" \
                -c /opt/kafka/config/kraft/server.properties
          envFrom:
            - configMapRef:
                name: kafka-config
          volumeMounts:
            - name: kafka-logs
              mountPath: /tmp/kraft-combined-logs
      containers:
        - name: kafka
          image: apache/kafka:3.9.0
          command:
            - /opt/kafka/bin/kafka-server-start.sh
            - /opt/kafka/config/kraft/server.properties
          envFrom:
            - configMapRef:
                name: kafka-config
          ports:
            - name: client
              containerPort: 9092
            - name: controller
              containerPort: 9093
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          volumeMounts:
            - name: kafka-logs
              mountPath: /tmp/kraft-combined-logs
      volumes:
        - name: kafka-logs
          emptyDir: {}
---
# ── Topic provisioning Job ────────────────────────────────────────────────────
# Runs after Kafka is ready and creates the content-events topic.
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  labels:
    app: kafka
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-topic-init
          image: apache/kafka:3.9.0
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              until /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --list > /dev/null 2>&1; do
                echo "  Kafka not ready yet, retrying in 5s..."
                sleep 5
              done
              echo "Kafka is ready. Creating topic content-events..."
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --create \
                --if-not-exists \
                --topic content-events \
                --partitions 1 \
                --replication-factor 1 \
                --config retention.ms=86400000 \
                --config cleanup.policy=delete
              echo "Topic created successfully."
              /opt/kafka/bin/kafka-topics.sh \
                --bootstrap-server kafka.dd-dev.svc.cluster.local:9092 \
                --describe --topic content-events